### ISSUE TITLE
v1.1.2 runtime error

### ISSUE THREAD

**Issue by beatgates** [niftylettuce/koa-better-error-handler#3]
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    **at Object.<anonymous> (D:\home\site\wwwroot\node_modules\koa-better-error-handler\lib\index.js:7:20)**
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by beatgates** [comment]
Looks like we forgot to put dependency on babel-runtime?

**Comment by niftylettuce** [comment]
can you submit a pull request @beatgates ?

**Comment by beatgates** [comment]
After I installed babel-runtime, got this error:

(node:404) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: ctx.onerror is not a function
Application has thrown an uncaught exception and is terminated:
TypeError: ctx.onerror is not a function
    at Array.onerror (D:\home\site\wwwroot\node_modules\koa\lib\application.js:133:34)
    at listener (D:\home\site\wwwroot\node_modules\on-finished\index.js:169:15)
    at onFinish (D:\home\site\wwwroot\node_modules\on-finished\index.js:100:5)
    at callback (D:\home\site\wwwroot\node_modules\ee-first\index.js:55:10)
    at Socket.onevent (D:\home\site\wwwroot\node_modules\ee-first\index.js:93:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)

**Comment by niftylettuce** [comment]
@beatgates please install latest version, `npm install --save koa-better-error-handler@latest`, thanks!
